variable "profile" {}
variable "region" {}
variable "availability_zone" {}
variable "pem_key" {}
variable "instance_type" {}
variable "name_tag" {}
variable "my_public_ip" {}
variable "subnet_id" {}
variable "vpc_id" {}
variable "public_ip" {}